# 📘 NumPy Tutorial: Numerical Foundations for Data Analysis

---

## ✨ What is NumPy?

NumPy (Numerical Python) is a foundational package for numerical computing in Python. It provides fast, memory-efficient arrays and a rich set of operations to manipulate them.

---

## 📦 Importing NumPy

In [1]:
import numpy as np


---

## 🔢 Creating Arrays

### From Python lists:

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


---

### Multidimensional array:

In [3]:
mat = np.array([[1, 2], [3, 4]])
print(mat)

[[1 2]
 [3 4]]


---

## 🧱 Array Attributes

In [4]:
print(arr.shape)      # Shape of array
print(arr.dtype)      # Data type
print(arr.ndim)       # Number of dimensions

(4,)
int64
1


---

## 🛠️ Creating Arrays with Defaults

In [5]:
np.zeros((2, 3))        # 2x3 array of zeros
np.ones((3,))           # 1D array of ones
np.arange(0, 10, 2)     # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)    # 5 evenly spaced points from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

--- 

## 📐 Array Indexing and Slicing

In [6]:
arr = np.array([10, 20, 30, 40])
print(arr[1])           # 20
print(arr[1:3])         # [20 30]
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat[1, 2])        # 6

20
[20 30]
6


---

## 🔁 Vectorized Operations

In [7]:
arr = np.array([1, 2, 3])
print(arr + 5)           # [6 7 8]
print(arr * 2)           # [2 4 6]

[6 7 8]
[2 4 6]


---

## 🧮 Mathematical Functions

In [8]:
np.mean(arr)
np.std(arr)
np.sum(arr)
np.max(arr)
np.min(arr)

np.int64(1)

---

## 🔄 Reshaping and Transposing

In [9]:
arr = np.arange(6).reshape(2, 3)  # 2 rows, 3 columns
print(arr)

print(arr.T)                     # Transpose

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
